# Connector configuration properties

# Credentials to authenticate on Control Center
# Passed via environment variables: CONNECTOR_USERNAME, CONNECTOR_PASSWORD

# Control Center backend URL (where the connector should connect to). Passed via environment variables.
connector.cc-url   = http://control-center-backend:3000
connector.name     = cloud-connector

# The url where clusters attached to Control Center via this Cloud Connector should send metrics
connector.base-url = http://control-center-connector:3200
