# Control Center configuration properties

# The url where clusters attached directly to Control Center Backend should send metrics
# In this demo we pass them through environment variables, because we need this URL in script.
# connector.base-url = http://control-center-backend:3000

# Following parameters can be provided in configuration file.
# In this demo we pass them through environment variables.
# account.admin.email =
# account.admin.password =